version: '3.3'

services:
  web:
    restart: unless-stopped
    build: ./services/web
    # command: python run.py run
    command: gunicorn --bind 0.0.0.0:5000 run:app
    expose: 
      - 5000

  nginx:
    restart: unless-stopped
    build: ./services/nginx
    ports:
      - 80:80
    depends_on:
      - web