version: '3.3'

services:
  web:
    restart: unless-stopped
    build: ./services/web
    # command: python run.py run
    command: gunicorn --bind 0.0.0.0:5000 run:app
    env_file:
      - .env
    expose: 
      - 5000

  nginx:
    restart: unless-stopped
    # image: jonasal/nginx-certbot:latest
    build: ./services/nginx
    # environment:
    #   - CERTBOT_EMAIL
    env_file:
      - ./services/nginx/nginx-certbot.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./services/nginx/user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - web

volumes:
  nginx_secrets: